version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: epilink-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: epilink
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
