#!/bin/sh

echo "Running pre-push checks..."

# Run backend tests
# echo "Running backend tests..."
# cd backend && npm run test -- --passWithNoTests || {
#   echo "Backend tests failed! Push aborted."
#   exit 1
# }
# cd ..

# Build frontend
echo "Building frontend..."
cd frontend && npm run build || {
  echo "Frontend build failed! Push aborted."
  exit 1
}
cd ..

# Build backend
echo "Building backend..."
cd backend && npm run build || {
  echo "Backend build failed! Push aborted."
  exit 1
}
cd ..

echo "All pre-push checks passed!"
